name: enrutatec
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.4
  flutter_svg: ^2.0.9
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  shared_preferences: ^2.2.1
  day_night_switcher: ^0.2.0+1
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  google_maps_flutter: ^2.5.0
  provider: ^6.0.5
  concentric_transition: ^1.0.3
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter_local_notifications: ^16.1.0
  flutter_easyloading: ^3.0.5
  github: ^9.20.0
  url_launcher: ^6.1.10
  uni_links: ^0.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/.
    